import createNextIntlPlugin from "next-intl/plugin";
import type { NextConfig } from "next";

const withNextIntl = createNextIntlPlugin("./i18n/request.ts");

const nextConfig: NextConfig = {
    transpilePackages: [
        "react-markdown",
        "remark-gfm",
        "rehype-sanitize",
        "unified",
        "bail",
        "is-plain-obj",
        "trough",
        "vfile",
        "vfile-message",
        "unist-util-stringify-position",
        "mdast-util-from-markdown",
        "mdast-util-to-markdown",
        "mdast-util-gfm",
        "mdast-util-gfm-autolink-literal",
        "mdast-util-gfm-footnote",
        "mdast-util-gfm-strikethrough",
        "mdast-util-gfm-table",
        "mdast-util-gfm-task-list-item",
        "micromark",
        "micromark-core-commonmark",
        "micromark-extension-gfm",
        "micromark-extension-gfm-autolink-literal",
        "micromark-extension-gfm-footnote",
        "micromark-extension-gfm-strikethrough",
        "micromark-extension-gfm-table",
        "micromark-extension-gfm-tagfilter",
        "micromark-extension-gfm-task-list-item",
        "micromark-util-character",
        "micromark-util-chunked",
        "micromark-util-classify-character",
        "micromark-util-combine-extensions",
        "micromark-util-decode-numeric-character-reference",
        "micromark-util-decode-string",
        "micromark-util-encode",
        "micromark-util-html-tag-name",
        "micromark-util-normalize-identifier",
        "micromark-util-resolve-all",
        "micromark-util-sanitize-uri",
        "micromark-util-subtokenize",
        "micromark-util-types",
        "remark-parse",
        "remark-rehype",
        "rehype-stringify",
        "hast-util-raw",
        "hast-util-to-html",
        "hast-util-sanitize",
        "hast-util-from-parse5",
        "hast-util-to-parse5",
        "hast-util-to-text",
        "hast-util-is-element",
        "hast-util-has-property",
        "hast-util-whitespace",
        "hastscript",
        "unist-util-visit",
        "unist-util-visit-parents",
        "unist-util-is",
        "unist-util-position",
        "unist-util-generated",
        "unist-util-remove-position",
        "property-information",
        "space-separated-tokens",
        "comma-separated-tokens",
        "web-namespaces",
        "zwitch",
        "extend",
        "ccount",
        "decode-named-character-reference",
        "character-entities",
        "devlop",
        "longest-streak",
        "mdast-util-phrasing-content",
        "mdast-util-find-and-replace",
        "mdast-util-to-hast",
        "mdast-util-definitions",
        "trim-lines",
    ],
    async headers() {
        return [
            {
                source: "/(.*)",
                headers: [
                    { key: "X-Content-Type-Options", value: "nosniff" },
                    { key: "X-Frame-Options", value: "DENY" },
                    { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
                    { key: "Permissions-Policy", value: "geolocation=(), microphone=(), camera=()" },
                    ...(process.env.NEXT_PUBLIC_APP_URL?.includes("localhost") ||
                        process.env.VERCEL_ENV === "preview"
                        ? [{ key: "X-Robots-Tag", value: "noindex, nofollow" }]
                        : []),
                ],
            },
        ];
    },
    serverExternalPackages: [
        "discord.js",
        "@discordjs/ws",
        "node-cron",
        "@react-pdf/renderer",
        "canvas",
    ],
    images: {
        remotePatterns: [
            {
                protocol: "https",
                hostname: "cdn.discordapp.com",
                pathname: "/icons/**",
            },
            {
                protocol: "https",
                hostname: "cdn.discordapp.com",
                pathname: "/avatars/**",
            },
            {
                protocol: "https",
                hostname: "cdn.discordapp.com",
                pathname: "/embed/avatars/**",
            },
        ],
    },
};

export default withNextIntl(nextConfig);
